/**
 * Next.js için temel importlar ve sayfa düzeni bileşenleri
 */
import type { Metadata } from "next";
// Google Fonts'tan Geist fontlarını import ediyoruz
import { Geist, Geist_Mono } from "next/font/google";
// Global CSS dosyasını import ediyoruz
import "./globals.css";
// Sayfa düzeni bileşenlerini import ediyoruz
import { Navbar } from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

// Geist Sans fontunu yapılandırıyoruz
// variable özelliği ile CSS değişkeni olarak kullanılabilir hale getiriyoruz
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Geist Mono (monospace) fontunu yapılandırıyoruz
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Sayfa meta verileri
 * Başlık ve açıklama bilgilerini içerir
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Ana sayfa düzeni bileşeni
 * Tüm sayfaların ortak yapısını oluşturur
 * @param children - Sayfa içeriğini temsil eden React düğümü
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // HTML lang özelliğini "en" (İngilizce) olarak ayarlıyoruz
    <html lang="en">
      {/* Font değişkenlerini ve antialiased özelliğini body'ye uyguluyoruz */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Üst navigasyon çubuğu */}
        <Navbar />
        {/* Ana sayfa içeriği */}
        {children}
        {/* Alt bilgi bölümü */}
        <Footer />
      </body>
    </html>
  );
}
